# GlobalBoosters Configuration
# Configure prices and durations for each booster type

# Maximum number of boosters that can be active at the same time
# Set to -1 for unlimited
max_active_boosters: 3

boosters:
  plant_growth:
    price: 500.0
    duration: 30  # minutes
  spawner_rate:
    price: 1500.0
    duration: 30
  exp_multiplier:
    price: 1000.0
    duration: 30
  mob_drop:
    price: 1200.0
    duration: 30
  mining_speed:
    price: 800.0
    duration: 30
  fishing_luck:
    price: 600.0
    duration: 30
  farming_fortune:
    price: 700.0
    duration: 30
  combat_damage:
    price: 2000.0
    duration: 30