max_active_boosters: 3

keep_effects_on_death: true

limited_supply_mode: false

max_supply_per_booster: 10

supply_reset_hour: 0

shop_gui_enabled: true

show_activator_name: true

negative_effects_enabled: true

# Control the volume of all plugin sounds. 1.0 is max, 0.0 is muted.
sound_volume: 1.0

  # Examples: UTC, GMT, America/New_York, Europe/London, Europe/Rome,
  # Asia/Tokyo, America/Los_Angeles, Australia/Sydney
# Full list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
scheduled_boosters:
  enabled: true
  timezone: "Europe/Rome"
  schedules:
    strength_morning:
      enabled: false
      type: STRENGTH
      hour: 10
      minute: 0
      duration: 30
      activator_name: "Server"
      days:
        - MONDAY
        - TUESDAY
        - WEDNESDAY
        - THURSDAY
        - FRIDAY
        - SATURDAY
        - SUNDAY
    exp_evening:
      enabled: false
      type: EXP_MULTIPLIER
      hour: 20
      minute: 0
      duration: 60
      activator_name: "Server"
      days:
        - FRIDAY
        - SATURDAY
        - SUNDAY
    speed_noon:
      enabled: false
      type: SPEED
      hour: 12
      minute: 0
      duration: 30
      activator_name: "Server"
      days:
        - SATURDAY
        - SUNDAY

random_scheduled_boosters:
  enabled: true
  interval_minutes: 30
  duration_minutes: 5
  activator_name: "Server"
  booster_pool:
    - PLANT_GROWTH
    - SPAWNER_RATE
    - EXP_MULTIPLIER
    - MOB_DROP
    - MINING_SPEED
    - FISHING_LUCK
    - FARMING_FORTUNE
    - COMBAT_DAMAGE
    - HASTE
    - RESISTANCE
    - JUMP_BOOST
    - REGENERATION
    - NIGHT_VISION
    - FIRE_RESISTANCE
    - SPEED
    - STRENGTH
    - NO_FALL_DAMAGE
    - HUNGER_SAVER
    - ARMOR_DURABILITY
    - KEEP_INVENTORY
    - FLY

boosters:
  plant_growth:
    enabled: true
    price: 500.0
    duration: 30
  spawner_rate:
    enabled: true
    price: 1500.0
    duration: 30
    multiplier: 2.0
  exp_multiplier:
    enabled: true
    price: 1000.0
    duration: 30
    multiplier: 2.0
  mob_drop:
    enabled: true
    price: 1200.0
    duration: 30
    multiplier: 2.0
  mining_speed:
    enabled: true
    price: 800.0
    duration: 30
    multiplier: 1.5
  fishing_luck:
    enabled: true
    price: 600.0
    duration: 30
    multiplier: 2.0
  farming_fortune:
    enabled: true
    price: 700.0
    duration: 30
    multiplier: 2.0
  combat_damage:
    enabled: true
    price: 2000.0
    duration: 30
    multiplier: 1.5
  haste:
    enabled: true
    price: 1000.0
    duration: 30
    multiplier: 2.0
  resistance:
    enabled: true
    price: 1500.0
    duration: 30
    multiplier: 2.0
  jump_boost:
    enabled: true
    price: 800.0
    duration: 30
    multiplier: 2.0
  regeneration:
    enabled: true
    price: 2000.0
    duration: 30
    multiplier: 1.0
  night_vision:
    enabled: true
    price: 600.0
    duration: 30
    multiplier: 1.0
  fire_resistance:
    enabled: true
    price: 1200.0
    duration: 30
    multiplier: 1.0
  speed:
    enabled: true
    price: 1000.0
    duration: 30
    multiplier: 2.0
  strength:
    enabled: true
    price: 2500.0
    duration: 30
    multiplier: 2.0
  no_fall_damage:
    enabled: true
    price: 800.0
    duration: 30
  hunger_saver:
    enabled: true
    price: 600.0
    duration: 30
    multiplier: 0.5
  armor_durability:
    enabled: true
    price: 1200.0
    duration: 30
    multiplier: 0.5
  keep_inventory:
    enabled: true
    price: 3000.0
    duration: 30
  fly:
    enabled: true
    price: 2500.0
    duration: 30
  slowness:
    enabled: true
    price: 10000.0
    duration: 1
    multiplier: 1.0
  mining_fatigue:
    enabled: true
    price: 10000.0
    duration: 1
    multiplier: 1.0
  weakness:
    enabled: true
    price: 10000.0
    duration: 1
    multiplier: 1.0
  poison:
    enabled: true
    price: 10000.0
    duration: 1
    multiplier: 1.0
  wither:
    enabled: true
    price: 10000.0
    duration: 1
    multiplier: 1.0
  blindness:
    enabled: true
    price: 10000.0
    duration: 1
    multiplier: 1.0
  hunger:
    enabled: true
    price: 10000.0
    duration: 1
    multiplier: 1.0
  nausea:
    enabled: true
    price: 10000.0
    duration: 1
    multiplier: 1.0