name: GlobalBoosters
version: '2.2-BETA'
main: com.Lino.globalBoosters.GlobalBoosters
api-version: '1.21'
depend: [Vault]
author: Lino
description: A comprehensive global boosters plugin for Minecraft servers

commands:
  boostshop:
    description: Open the booster shop GUI
    usage: /<command>
    aliases: [bs]
    permission: globalboosters.shop
  booster:
    description: Main booster management command
    usage: /<command> [give/reload/stats]
    aliases: [boost, gb]
    permission: globalboosters.admin
  globalboosters:
    description: Main plugin command
    usage: /<command> [help/list]
    aliases: [gbooster, globalboost]

permissions:
  globalboosters.shop:
    description: Allows access to the booster shop
    default: true
  globalboosters.use:
    description: Allows using booster items
    default: true
  globalboosters.use.plant_growth:
    description: Allows using Plant Growth booster
    default: false
  globalboosters.use.spawner_rate:
    description: Allows using Spawner Rate booster
    default: false
  globalboosters.use.exp_multiplier:
    description: Allows using Experience booster
    default: false
  globalboosters.use.mob_drop:
    description: Allows using Mob Drop booster
    default: false
  globalboosters.use.mining_speed:
    description: Allows using Mining Speed booster
    default: false
  globalboosters.use.fishing_luck:
    description: Allows using Fishing Luck booster
    default: false
  globalboosters.use.farming_fortune:
    description: Allows using Farming Fortune booster
    default: false
  globalboosters.use.combat_damage:
    description: Allows using Combat Damage booster
    default: false
  globalboosters.use.haste:
    description: Allows using Haste booster
    default: false
  globalboosters.use.resistance:
    description: Allows using Resistance booster
    default: false
  globalboosters.use.jump_boost:
    description: Allows using Jump Boost booster
    default: false
  globalboosters.use.regeneration:
    description: Allows using Regeneration booster
    default: false
  globalboosters.use.night_vision:
    description: Allows using Night Vision booster
    default: false
  globalboosters.use.fire_resistance:
    description: Allows using Fire Resistance booster
    default: false
  globalboosters.use.speed:
    description: Allows using Speed booster
    default: false
  globalboosters.use.strength:
    description: Allows using Strength booster
    default: false
  globalboosters.use.no_fall_damage:
    description: Allows using No Fall Damage booster
    default: false
  globalboosters.use.hunger_saver:
    description: Allows using Hunger Saver booster
    default: false
  globalboosters.use.armor_durability:
    description: Allows using Armor Durability booster
    default: false
  globalboosters.use.keep_inventory:
    description: Allows using Keep Inventory booster
    default: false
  globalboosters.use.fly:
    description: Allows using Fly booster
    default: false
  globalboosters.admin:
    description: Admin permission for all features
    default: op
    children:
      globalboosters.shop: true
      globalboosters.use: true
      globalboosters.admin.give: true
      globalboosters.admin.reload: true
      globalboosters.admin.stats: true
  globalboosters.admin.give:
    description: Allows giving boosters to players
    default: op
  globalboosters.admin.reload:
    description: Allows reloading the plugin configuration
    default: op
  globalboosters.admin.stats:
    description: Allows viewing booster statistics
    default: op
  globalboosters.fly.bypass:
    description: Keeps flight ability when fly booster expires
    default: op