name: GlobalBoosters
version: '1.6-BETA'
main: com.Lino.globalBoosters.GlobalBoosters
api-version: '1.21'
depend: [Vault]
author: Lino
description: A comprehensive global boosters plugin for Minecraft servers

commands:
  boostshop:
    description: Open the booster shop GUI
    usage: /<command>
    aliases: [bs]
    permission: globalboosters.shop
  booster:
    description: Main booster management command
    usage: /<command> [give/reload/stats]
    aliases: [boost, gb]
    permission: globalboosters.admin
  globalboosters:
    description: Main plugin command
    usage: /<command> [help/list]
    aliases: [gbooster, globalboost]

permissions:
  globalboosters.shop:
    description: Allows access to the booster shop
    default: true
  globalboosters.use:
    description: Allows using booster items
    default: true
  globalboosters.admin:
    description: Admin permission for all features
    default: op
    children:
      globalboosters.shop: true
      globalboosters.use: true
      globalboosters.admin.give: true
      globalboosters.admin.reload: true
      globalboosters.admin.stats: true
  globalboosters.admin.give:
    description: Allows giving boosters to players
    default: op
  globalboosters.admin.reload:
    description: Allows reloading the plugin configuration
    default: op
  globalboosters.admin.stats:
    description: Allows viewing booster statistics
    default: op